version: '3.7'

services:
  app:
    build: ./rate_limiter
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db
      - redis

  #localhost:8083/student to test
  #response : [{"studentId":19,"name":"Ansh","clas":"A"}]
  student_management:
    build: ./student_management
    image: docker/playground:student_management

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: Password123@
      MYSQL_ROOT_PASSWORD: Password123@

  redis:
    image: redis:6.2.3

  web:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.static.yml:/etc/traefik/traefik.static.yml # static config
      - ./traefik/traefik.dynamic.yml:/etc/traefik/traefik.dynamic.yml # dynamic config
