http:
  routers:
    # define a connection between the request and the service.
    to-app:
      rule: PathPrefix(`/rails`)
      service: app
      entryPoints:
        - http
      middlewares:
        - redirect

    to-java:
      rule: PathPrefix(`/java`)
      service: stm
      entryPoints:
        - http
      middlewares:
        - strip-java

  middlewares:
    redirect:
      redirectScheme:
        scheme: http
    strip-java:
      stripPrefix:
        prefixes:
          - /java

  # Add the service
  services:
    app:
      loadBalancer:
        servers:
          - url: "http://app:3000/"
    stm:
      loadBalancer:
        servers:
          - url: "http://student_management:8082/"
